sudo: false

language: node_js

node_js:
  - '6.9'

branches:
  only:
    - master
    - /^greenkeeper/.*$/

install:
  - npm install -g gulp
  - npm install

cache:
  directories:
    - node_modules

script:
 - npm run test

after_success:
 - bithound check git@github.com:coveo/react-vapor.git
 - npm run report-coverage
