# Site settings
title: Vapor CSS
email: styleguide@coveo.com
description: Vapor is Coveo's collection of UI styles used in Coveo Cloud Administration Console.
twitter_username: coveo
github_username: Coveo
github_repo: https://github.com/coveo/react-vapor/

# Collections
collections:
    components:
        output: false

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
sass:
    sass_dir: _sass
    style: :compressed

# Server
source: docs
destination: _gh_pages
baseurl: ''
url: 'http://vapor.surge.sh/'
